name: "Binary Build"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Binary Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Build & test"
        run: |
          env GOOS=windows GOARCH=amd64 go build -o /tmp/integrity.exe main.go
          env GOOS=linux GOARCH=amd64 go build -o /tmp/integrity-linux main.go
          env GOOS=darwin GOARCH=amd64 go build -o /tmp/integrity main.go

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            /tmp/integrity*
